eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8988

---
spring:
  profiles: application_1
  server:
  port: 8009 
  
---  
cassandra:
  port: 9042
  contact-points: localhost
  keyspace-name: rest_workshop

---
    
  

